version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  application:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      SESSION_SECRET: super-duper-s3cret
    ports:
      - "3000:3000"      
      - "3010:3010"     
    depends_on:
      - postgres
